delimiter: "comma"
skip_lines: 1
field_count: 6
filename_format: null
datetime_format: null
# timestamp_in_filename: null


# ftype can be 'int', 'float', 'datetime'

fields:
    - name: "timestamp"
      colno: 2
      ftype: datetime
      factor: 1
      ifnull: null
      nullval: null
      label: 'Time'
      units: 'IST'

    - name: "altitude"
      colno: 6
      ftype: float
      factor: 1
      ifnull: null
      nullval: null
      label: 'Height'
      units: 'km'

    - name: "pressure"
      colno: 7
      ftype: float
      factor: 1
      ifnull: null
      nullval: null
      label: 'Pressure'
      units: 'mb'

    - name: "temperature"
      colno: 8
      ftype: float
      factor: 1
      ifnull: null
      nullval: null
      label: 'Temperature'
      units: 'deg'

    - name: "humidity"
      colno: 10
      ftype: float
      factor: 1
      ifnull: null
      nullval: null
      label: 'Relative Humidity'
      units: 'RH%'

    - name: "ascrate"
      colno: 17
      ftype: float
      factor: 1
      ifnull: null
      nullval: null
      label: 'Ascent Rate'
      units: 'm/s'



interpolation:
  pivot: "altitude"
  
  ## meta data need to folder reading
  start: 2
  stop: 20
  step: 0.15


output: 
  fields: ["altitude", "pressure", "temperature", "humidity"]


plot:
  file:
    - type: line
      xaxis: null
      yaxis: 'altitude'
      title: 'first plot'
      fields: ["pressure", "temperature", "humidity", "ascrate"]
    
    - type: line
      xaxis: 'timestamp'
      yaxis: null
      title: 'Second plot'
      fields: ['altitude', 'pressure', 'temperature', 'humidity', 'ascrate']


parsers:
  datetime: DATETIME_PARSER
  filename: FILENAME_PARSER

encoders:
  datetime: DATETIME_ENCODER
  filename: FILENAME_ENCODER




