#configuration template for data in assets/data/rs/ folder

delimiter: "comma"
datetime_format: null
skip_lines: 1
field_count: 6
filename_format: "GPSRS%Y%m%d.CSV"
timestamp_in_filename: true


# ftype can be 'int', 'float', 'datetime'

fields:
    - name: "height"
      colno: 2
      ftype: float
      factor: 0.001
      ifnull: null
      nullval: null
      label: 'Height'
      units: 'km'

    - name: "ws"
      colno: 3
      ftype: float
      factor: 1
      ifnull: null
      nullval: null
      label: 'Wind Speed'
      units: 'm/s'

    - name: "wd"
      colno: 4
      ftype: float
      factor: 1
      ifnull: null
      nullval: null
      label: 'Wind Direction'
      units: 'deg'

    - name: "temperature"
      colno: 5
      ftype: float
      factor: 1
      ifnull: null
      nullval: null
      label: 'Temperature'
      units: 'deg-centi'

    - name: "pressure"
      colno: 6
      ftype: float
      factor: 1
      ifnull: null
      nullval: null
      label: 'Pressure'
      units: 'mbar'

    - name: "humidity"
      colno: 7
      ftype: float
      factor: 1
      ifnull: null
      nullval: null
      label: 'Humidity'
      units: 'g/m3'

interpolation:
  pivot: "height"
  
  ## meta-data needed for folder reading
  start: 0.36
  stop: 31
  step: 0.005


#Useful for writing data to output files( flash memory)
output: 
  fields: ["height", "ws", "wd", "temperature"]


plot:
  file:
    - type: line
      xaxis: height
      yaxis: null
      title: 'Line Plot with Height as x-axis'
      fields: ['ws','wd','temperature','pressure','humidity']
    
  
  folder:
    - type: line
      xaxis: 'filestamp'
      yaxis: 'height'
      title: 'Line plot'
      fields: ['ws', 'wd', 'temperature', 'pressure', 'humidity']


parsers:
  datetime: DATETIME_PARSER
  filename: FILENAME_PARSER

encoders:
  datetime: DATETIME_ENCODER
  filename: FILENAME_ENCODER
